ALTER TABLE `BudgetVersion`
  ADD COLUMN `executorName` VARCHAR(191) NULL,
  ADD COLUMN `profitPercentage` DECIMAL(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `profitAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `vatPercentage` DECIMAL(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `vatAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `financingPercentage` DECIMAL(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `financingAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0;
